// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testUnfolloweds(t *testing.T) {
	t.Parallel()

	query := Unfolloweds()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testUnfollowedsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Unfollowed{}
	if err = randomize.Struct(seed, o, unfollowedDBTypes, true, unfollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Unfolloweds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUnfollowedsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Unfollowed{}
	if err = randomize.Struct(seed, o, unfollowedDBTypes, true, unfollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Unfolloweds().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Unfolloweds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUnfollowedsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Unfollowed{}
	if err = randomize.Struct(seed, o, unfollowedDBTypes, true, unfollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UnfollowedSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Unfolloweds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUnfollowedsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Unfollowed{}
	if err = randomize.Struct(seed, o, unfollowedDBTypes, true, unfollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := UnfollowedExists(ctx, tx, o.UID)
	if err != nil {
		t.Errorf("Unable to check if Unfollowed exists: %s", err)
	}
	if !e {
		t.Errorf("Expected UnfollowedExists to return true, but got false.")
	}
}

func testUnfollowedsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Unfollowed{}
	if err = randomize.Struct(seed, o, unfollowedDBTypes, true, unfollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	unfollowedFound, err := FindUnfollowed(ctx, tx, o.UID)
	if err != nil {
		t.Error(err)
	}

	if unfollowedFound == nil {
		t.Error("want a record, got nil")
	}
}

func testUnfollowedsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Unfollowed{}
	if err = randomize.Struct(seed, o, unfollowedDBTypes, true, unfollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Unfolloweds().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testUnfollowedsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Unfollowed{}
	if err = randomize.Struct(seed, o, unfollowedDBTypes, true, unfollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Unfolloweds().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testUnfollowedsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	unfollowedOne := &Unfollowed{}
	unfollowedTwo := &Unfollowed{}
	if err = randomize.Struct(seed, unfollowedOne, unfollowedDBTypes, false, unfollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}
	if err = randomize.Struct(seed, unfollowedTwo, unfollowedDBTypes, false, unfollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = unfollowedOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = unfollowedTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Unfolloweds().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testUnfollowedsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	unfollowedOne := &Unfollowed{}
	unfollowedTwo := &Unfollowed{}
	if err = randomize.Struct(seed, unfollowedOne, unfollowedDBTypes, false, unfollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}
	if err = randomize.Struct(seed, unfollowedTwo, unfollowedDBTypes, false, unfollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = unfollowedOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = unfollowedTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Unfolloweds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func unfollowedBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Unfollowed) error {
	*o = Unfollowed{}
	return nil
}

func unfollowedAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Unfollowed) error {
	*o = Unfollowed{}
	return nil
}

func unfollowedAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Unfollowed) error {
	*o = Unfollowed{}
	return nil
}

func unfollowedBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Unfollowed) error {
	*o = Unfollowed{}
	return nil
}

func unfollowedAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Unfollowed) error {
	*o = Unfollowed{}
	return nil
}

func unfollowedBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Unfollowed) error {
	*o = Unfollowed{}
	return nil
}

func unfollowedAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Unfollowed) error {
	*o = Unfollowed{}
	return nil
}

func unfollowedBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Unfollowed) error {
	*o = Unfollowed{}
	return nil
}

func unfollowedAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Unfollowed) error {
	*o = Unfollowed{}
	return nil
}

func testUnfollowedsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Unfollowed{}
	o := &Unfollowed{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, unfollowedDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Unfollowed object: %s", err)
	}

	AddUnfollowedHook(boil.BeforeInsertHook, unfollowedBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	unfollowedBeforeInsertHooks = []UnfollowedHook{}

	AddUnfollowedHook(boil.AfterInsertHook, unfollowedAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	unfollowedAfterInsertHooks = []UnfollowedHook{}

	AddUnfollowedHook(boil.AfterSelectHook, unfollowedAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	unfollowedAfterSelectHooks = []UnfollowedHook{}

	AddUnfollowedHook(boil.BeforeUpdateHook, unfollowedBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	unfollowedBeforeUpdateHooks = []UnfollowedHook{}

	AddUnfollowedHook(boil.AfterUpdateHook, unfollowedAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	unfollowedAfterUpdateHooks = []UnfollowedHook{}

	AddUnfollowedHook(boil.BeforeDeleteHook, unfollowedBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	unfollowedBeforeDeleteHooks = []UnfollowedHook{}

	AddUnfollowedHook(boil.AfterDeleteHook, unfollowedAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	unfollowedAfterDeleteHooks = []UnfollowedHook{}

	AddUnfollowedHook(boil.BeforeUpsertHook, unfollowedBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	unfollowedBeforeUpsertHooks = []UnfollowedHook{}

	AddUnfollowedHook(boil.AfterUpsertHook, unfollowedAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	unfollowedAfterUpsertHooks = []UnfollowedHook{}
}

func testUnfollowedsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Unfollowed{}
	if err = randomize.Struct(seed, o, unfollowedDBTypes, true, unfollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Unfolloweds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUnfollowedsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Unfollowed{}
	if err = randomize.Struct(seed, o, unfollowedDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(unfollowedColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Unfolloweds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUnfollowedsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Unfollowed{}
	if err = randomize.Struct(seed, o, unfollowedDBTypes, true, unfollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUnfollowedsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Unfollowed{}
	if err = randomize.Struct(seed, o, unfollowedDBTypes, true, unfollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UnfollowedSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUnfollowedsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Unfollowed{}
	if err = randomize.Struct(seed, o, unfollowedDBTypes, true, unfollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Unfolloweds().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	unfollowedDBTypes = map[string]string{`UID`: `bigint`}
	_                 = bytes.MinRead
)

func testUnfollowedsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(unfollowedPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(unfollowedAllColumns) == len(unfollowedPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Unfollowed{}
	if err = randomize.Struct(seed, o, unfollowedDBTypes, true, unfollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Unfolloweds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, unfollowedDBTypes, true, unfollowedPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testUnfollowedsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(unfollowedAllColumns) == len(unfollowedPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Unfollowed{}
	if err = randomize.Struct(seed, o, unfollowedDBTypes, true, unfollowedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Unfolloweds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, unfollowedDBTypes, true, unfollowedPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(unfollowedAllColumns, unfollowedPrimaryKeyColumns) {
		fields = unfollowedAllColumns
	} else {
		fields = strmangle.SetComplement(
			unfollowedAllColumns,
			unfollowedPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := UnfollowedSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testUnfollowedsUpsert(t *testing.T) {
	t.Parallel()

	if len(unfollowedAllColumns) == len(unfollowedPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Unfollowed{}
	if err = randomize.Struct(seed, &o, unfollowedDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Unfollowed: %s", err)
	}

	count, err := Unfolloweds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, unfollowedDBTypes, false, unfollowedPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Unfollowed struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Unfollowed: %s", err)
	}

	count, err = Unfolloweds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
